// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SelectListNamespaceDetails() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p id=\"result\" class=\"\"><div class=\"col-sm-12 mt-4\" id=\"namespaceValuesTable\"><input type=\"hidden\" name=\"namespace\" value=\"braza-tokens-dashboard\"><h4>Variáveis no Namespace: braza-tokens-dashboard</h4><table class=\"table table-bordered\"><thead><tr><th>Key</th><th>Value</th></tr></thead> <tbody><tr><td>teste1</td><td>teste1</td></tr><tr><td>MONGO_WHITELIST_COLLECTION</td><td>withelist</td></tr><tr><td>BRAZA_TOKENS_API_URL</td><td>https://sandbox-tokens.getbraza.uk/api</td></tr><tr><td>MONGO_BRAZA_TOKENS_DATABASE</td><td>Braza-Tokens</td></tr></tbody></table></div></p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
